server:
  port: 8781

eureka: #注册到注册中心
  client:
    serviceUrl:
#      defaultZone: http://119.23.27.78:8761/eureka
      defaultZone: http://localhost:8761/eureka/


spring:
  application:
    name: cloud-config #客户端名称
# 从git获取配置文件
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wsklnso1/mall_hsj.git #配置git仓库地址
          #指定搜索路径，config-server会自动搜索根目录和指定目录（逗号分隔）下的文件
          search-paths: config-file/first-config

  #从本地获取配置文件
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
##          search-locations: D:/project/IDEAProjects/learn/learn-cloud-config/cloud-config-repo
##          search-locations: D:/GitHub/learn/learn-cloud-config/cloud-config-repo
#          search-locations: D:/GitHub/learn/learn-cloud-config/cloud-config-core,D:/GitHub/learn/learn-cloud-config/cloud-config-single/{application}
##          search-locations: D:/project/IDEAProjects/learn/learn-cloud-config/cloud-config-core,D:/project/IDEAProjects/learn/learn-cloud-config/cloud-config-single/{application}