spring:
  #profiles:
    #active: dev 
  application:
     name: mall-hsj-zuul-gateway
     
server:
   port: 9090
   
eureka: 
   client:
      serviceUrl:
         defaultZone: http://server1:8001/eureka/

zuul:
   SendErrorFilter:
      error:
         disable: true
   routes:
      admin:
         path:  /admin/**
         #url: http://localhost:9010/hello
         serviceId: mall-hsj-admin
