spring:
   application:
      name: mall-hsj-eureka

server:
   port: 8761
eureka:
   instance:
      hostname: eureka1
      leaseRenewalIntervalInSeconds: 1
      leaseExpirationDurationInSeconds: 2
   client:
      serviceUrl:
         defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      fetch-registry: false
      register-with-eureka: false
   server:
      enableSelfPreservation: false



